"""Verifies the Alembic migration itself runs successfully — both directions.

This is distinct from `test_database_connection.py` (which checks the
schema produced via `Base.metadata.create_all`, driven by the ORM models
directly): this test invokes the real `alembic` CLI against a disposable,
purpose-built database, so a mistake made only inside the migration file
itself (as opposed to the ORM models it was generated from) is still
caught.

A dedicated database (not just a dedicated schema) is created and dropped
for this test, via a raw asyncpg connection in autocommit mode — `CREATE
DATABASE`/`DROP DATABASE` cannot run inside a transaction block, which
rules out using the shared SQLAlchemy engine/session fixtures here.
Migrations are run via `subprocess` (the real `alembic` CLI as a fresh
process) rather than Alembic's Python API in-process, specifically to
avoid interacting with this application's cached `get_settings()` /
`get_engine()` singletons, which are process-lifetime-scoped and would
otherwise make a second, differently-configured migration run within the
same test process unreliable.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import asyncpg
import pytest

from app.core.config import get_settings

BACKEND_ROOT = Path(__file__).resolve().parents[2]
TEST_DB_NAME = "careeros_alembic_migration_test"


def _admin_dsn(settings_database_url: str) -> str:
    """The `postgresql://` (sync, asyncpg-driver-less) DSN for admin
    connections, derived from the app's async SQLAlchemy URL.
    """
    return settings_database_url.replace("postgresql+asyncpg://", "postgresql://").rsplit("/", 1)[0]


@pytest.fixture
async def migration_test_database_url() -> str:
    """Creates a disposable database for this test only, and drops it afterward."""
    settings = get_settings()
    admin_dsn = _admin_dsn(settings.database_url)

    admin_conn = await asyncpg.connect(admin_dsn + "/postgres")
    try:
        await admin_conn.execute(f'DROP DATABASE IF EXISTS "{TEST_DB_NAME}" WITH (FORCE)')
        await admin_conn.execute(f'CREATE DATABASE "{TEST_DB_NAME}"')
    finally:
        await admin_conn.close()

    yield f"postgresql+asyncpg://{admin_dsn.split('://', 1)[1]}/{TEST_DB_NAME}"

    admin_conn = await asyncpg.connect(admin_dsn + "/postgres")
    try:
        await admin_conn.execute(f'DROP DATABASE IF EXISTS "{TEST_DB_NAME}" WITH (FORCE)')
    finally:
        await admin_conn.close()


def _run_alembic(*args: str, database_url: str) -> subprocess.CompletedProcess[str]:
    env = {**os.environ, "DATABASE_URL": database_url}
    return subprocess.run(  # noqa: S603 — fixed, non-shell argv; not user-controlled input
        [sys.executable, "-m", "alembic", *args],
        cwd=BACKEND_ROOT,
        env=env,
        capture_output=True,
        text=True,
        check=False,
    )


@pytest.mark.asyncio
async def test_migration_upgrade_creates_all_tables(migration_test_database_url: str) -> None:
    result = _run_alembic("upgrade", "head", database_url=migration_test_database_url)
    assert result.returncode == 0, result.stderr

    conn = await asyncpg.connect(
        migration_test_database_url.replace("postgresql+asyncpg://", "postgresql://")
    )
    try:
        tables = {
            row["tablename"]
            for row in await conn.fetch("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")
        }
    finally:
        await conn.close()

    assert {
        "users",
        "candidate_profiles",
        "resumes",
        "jobs",
        "job_matches",
        "applications",
        "profiles",
        "skills",
        "experience",
        "education",
        "resume_metadata",
        "generated_resumes",
        "generated_cover_letters",
    }.issubset(tables)


@pytest.mark.asyncio
async def test_migration_creates_working_profiles_singleton_constraint(
    migration_test_database_url: str,
) -> None:
    """Milestone 4's `ix_profiles_singleton` (a unique index on the
    constant expression `(true)`) is hand-adjusted from Alembic's
    autogenerated output (Postgres requires the extra grouping parens
    around a bare boolean literal — found by actually running this
    migration, see `docs/adr/0012-profile-management.md`). This test
    proves that fix is actually present and effective in the migration
    itself, not only in the ORM model.
    """
    result = _run_alembic("upgrade", "head", database_url=migration_test_database_url)
    assert result.returncode == 0, result.stderr

    conn = await asyncpg.connect(
        migration_test_database_url.replace("postgresql+asyncpg://", "postgresql://")
    )
    try:
        await conn.execute(
            "INSERT INTO profiles (id, full_name, email) VALUES (gen_random_uuid(), 'First', 'first@example.com')"
        )
        with pytest.raises(asyncpg.UniqueViolationError):
            await conn.execute(
                "INSERT INTO profiles (id, full_name, email) "
                "VALUES (gen_random_uuid(), 'Second', 'second@example.com')"
            )
    finally:
        await conn.close()


@pytest.mark.asyncio
async def test_migration_adds_profile_scoring_columns_to_job_matches(
    migration_test_database_url: str,
) -> None:
    """Milestone 5's `980eb04284d4` migration alters an existing table
    (`job_matches`, from Milestone 2) rather than creating a new one —
    proves `profile_id`/`matched_skills`/`missing_skills` exist and
    `user_id` is now nullable, matching `docs/adr/0013-score-against-profile-not-user.md`.
    """
    result = _run_alembic("upgrade", "head", database_url=migration_test_database_url)
    assert result.returncode == 0, result.stderr

    conn = await asyncpg.connect(
        migration_test_database_url.replace("postgresql+asyncpg://", "postgresql://")
    )
    try:
        columns = {
            row["column_name"]: row["is_nullable"]
            for row in await conn.fetch(
                "SELECT column_name, is_nullable FROM information_schema.columns "
                "WHERE table_name = 'job_matches'"
            )
        }
    finally:
        await conn.close()

    assert columns["profile_id"] == "YES"
    assert columns["matched_skills"] == "NO"
    assert columns["missing_skills"] == "NO"
    assert columns["user_id"] == "YES"  # relaxed from NOT NULL — no registration flow exists yet


@pytest.mark.asyncio
async def test_migration_downgrade_then_upgrade_again_succeeds(migration_test_database_url: str) -> None:
    """The real regression this test exists for: downgrading and
    re-upgrading must both succeed — this specifically caught a real bug
    during development (the native `application_status` Postgres enum
    type wasn't dropped by the autogenerated downgrade, so re-upgrading
    failed with "type already exists" until the migration was corrected).
    """
    up_result = _run_alembic("upgrade", "head", database_url=migration_test_database_url)
    assert up_result.returncode == 0, up_result.stderr

    down_result = _run_alembic("downgrade", "base", database_url=migration_test_database_url)
    assert down_result.returncode == 0, down_result.stderr

    conn = await asyncpg.connect(
        migration_test_database_url.replace("postgresql+asyncpg://", "postgresql://")
    )
    try:
        tables = {
            row["tablename"]
            for row in await conn.fetch("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")
        }
    finally:
        await conn.close()
    assert tables == {"alembic_version"}

    up_again_result = _run_alembic("upgrade", "head", database_url=migration_test_database_url)
    assert up_again_result.returncode == 0, up_again_result.stderr
