"""add planning persistence tables

Revision ID: 3633f5cc813a
Revises: 5c7e8f2a1b4d
Create Date: 2026-09-20 14:46:01.277052
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3633f5cc813a'
down_revision: str | None = '5c7e8f2a1b4d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('intention', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plans_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plans'))
    )
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_table('plan_items',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('item_type', sa.Enum('transport', 'activity', 'food', 'accommodation', 'shopping', 'service', 'other', name='plan_item_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_plan_items_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_items'))
    )
    op.create_index(op.f('ix_plan_items_plan_id'), 'plan_items', ['plan_id'], unique=False)
    op.create_table('planning_constraints',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('budget_max', 'budget_min', 'time_max', 'time_min', 'distance_max', 'group_size', 'preference', 'requirement', name='constraint_type'), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('numeric_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_planning_constraints_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_constraints'))
    )
    op.create_index(op.f('ix_planning_constraints_plan_id'), 'planning_constraints', ['plan_id'], unique=False)
    op.create_table('planning_contexts',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('group_size', sa.Integer(), server_default='1', nullable=False),
    sa.Column('transport_mode', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name=op.f('fk_planning_contexts_plan_id_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_planning_contexts')),
    sa.UniqueConstraint('plan_id', name=op.f('uq_planning_contexts_plan_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("planning_contexts")

    op.drop_index(
        op.f("ix_planning_constraints_plan_id"),
        table_name="planning_constraints",
    )
    op.drop_table("planning_constraints")

    op.drop_index(
        op.f("ix_plan_items_plan_id"),
        table_name="plan_items",
    )
    op.drop_table("plan_items")

    op.drop_index(
        op.f("ix_plans_user_id"),
        table_name="plans",
    )
    op.drop_table("plans")

    op.execute("DROP TYPE IF EXISTS plan_item_type")
    op.execute("DROP TYPE IF EXISTS constraint_type")

    # ### end Alembic commands ###
 