"""use clock_timestamp for created_at and updated_at defaults

Revision ID: 4f9e6c86a995
Revises: 3bbfa3cd78bd
Create Date: 2026-07-21 19:13:21.135930

Hand-written, not autogenerated: Alembic's `--autogenerate` does not
reliably diff server-side default *expressions* (it detected no change
here even though the model's `server_default` changed from `now()` to
`clock_timestamp()`), so this migration's `upgrade`/`downgrade` bodies
were written directly against the `TimestampMixin`/`CreatedAtMixin` change
in `app/infrastructure/db/mixins.py`.

Why this change: Postgres's `now()` returns the *transaction's* start
time — identical for every statement in the same transaction. A single
batch job-ingestion run (Milestone 3) can insert many `Job` rows in one
transaction, so with `now()` they'd all get an identical `created_at`,
breaking the newest-first ordering `SqlAlchemyJobRepository.list_jobs()`
depends on. `clock_timestamp()` returns the actual wall-clock time at each
statement's execution, giving each row a distinct, correctly-ordered
timestamp even within one transaction. Found by running the pagination
test against real Postgres, not assumed.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f9e6c86a995"
down_revision: str | None = "3bbfa3cd78bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Every table has created_at; all but job_matches also have updated_at
# (see docs/architecture/database-design.md — a match is a point-in-time
# snapshot, not a mutable record).
_TABLES_WITH_CREATED_AT = ("users", "candidate_profiles", "resumes", "jobs", "job_matches", "applications")
_TABLES_WITH_UPDATED_AT = ("users", "candidate_profiles", "resumes", "jobs", "applications")


def upgrade() -> None:
    for table in _TABLES_WITH_CREATED_AT:
        op.alter_column(table, "created_at", server_default=sa.text("clock_timestamp()"))
    for table in _TABLES_WITH_UPDATED_AT:
        op.alter_column(table, "updated_at", server_default=sa.text("clock_timestamp()"))


def downgrade() -> None:
    for table in _TABLES_WITH_CREATED_AT:
        op.alter_column(table, "created_at", server_default=sa.text("now()"))
    for table in _TABLES_WITH_UPDATED_AT:
        op.alter_column(table, "updated_at", server_default=sa.text("now()"))
