"""add profile management tables

Revision ID: a9b65b32aeda
Revises: 4f9e6c86a995
Create Date: 2026-07-23 22:32:50.234777

Adds `profiles` (a deliberately standalone, singleton table — see
`docs/adr/0012-profile-management.md`) and its child tables `skills`,
`experience`, `education`, `resume_metadata`. Does not touch `users` or
`candidate_profiles` (Milestone 2) — those are left exactly as they were.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a9b65b32aeda"
down_revision: str | None = "4f9e6c86a995"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('years_experience', sa.Integer(), server_default='0', nullable=False),
    sa.Column('preferred_job_title', sa.String(length=255), nullable=True),
    sa.Column('preferred_location', sa.String(length=255), nullable=True),
    sa.Column('salary_expectation', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('remote_preference', sa.Enum('onsite', 'hybrid', 'remote', 'flexible', name='remote_preference'), server_default='flexible', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profiles'))
    )
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=False)
    op.create_index('ix_profiles_singleton', 'profiles', [sa.text('(true)')], unique=True)
    op.create_table('education',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('qualification', sa.String(length=255), nullable=False),
    sa.Column('field_of_study', sa.String(length=255), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=False),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_education_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education'))
    )
    op.create_index(op.f('ix_education_profile_id'), 'education', ['profile_id'], unique=False)
    op.create_table('experience',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('currently_working', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_experience_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience'))
    )
    op.create_index(op.f('ix_experience_profile_id'), 'experience', ['profile_id'], unique=False)
    op.create_table('resume_metadata',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('clock_timestamp()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_resume_metadata_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_metadata'))
    )
    op.create_index(op.f('ix_resume_metadata_profile_id'), 'resume_metadata', ['profile_id'], unique=False)
    op.create_table('skills',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('fk_skills_profile_id_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('profile_id', 'name', name='uq_skills_profile_id_name')
    )
    op.create_index(op.f('ix_skills_profile_id'), 'skills', ['profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skills_profile_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_resume_metadata_profile_id'), table_name='resume_metadata')
    op.drop_table('resume_metadata')
    op.drop_index(op.f('ix_experience_profile_id'), table_name='experience')
    op.drop_table('experience')
    op.drop_index(op.f('ix_education_profile_id'), table_name='education')
    op.drop_table('education')
    op.drop_index('ix_profiles_singleton', table_name='profiles')
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_table('profiles')
    # ### end Alembic commands ###

    # Manually added: as with `application_status` in
    # 3bbfa3cd78bd_initial_database_schema.py, Alembic's autogenerate does
    # not emit a DROP TYPE for native Postgres enums when the table using
    # them is dropped. Added proactively this time (found once already in
    # Milestone 3) rather than waiting to hit "type already exists" again.
    sa.Enum(name='remote_preference').drop(op.get_bind(), checkfirst=True)
