from __future__ import annotations

from builtins import list as builtins_list
from typing import Protocol
from uuid import UUID

from app.domain.entities.action import Action
from app.domain.entities.approval import Approval
from app.domain.entities.audit_log import AuditLog
from app.domain.entities.event import Event
from app.domain.entities.incident import Incident


class EventRepository(Protocol):
    async def list(self) -> builtins_list[Event]: ...
    async def list_for_incident(self, *, incident_id: UUID) -> builtins_list[Event]: ...
    async def create(self, event: Event) -> Event: ...
    async def update(self, event: Event) -> Event: ...


class IncidentRepository(Protocol):
    async def list(self) -> builtins_list[Incident]: ...
    async def get_by_id(self, *, incident_id: UUID) -> Incident | None: ...
    async def create(self, incident: Incident) -> Incident: ...
    async def get_active_for_service(self, *, service_id: UUID) -> Incident | None: ...
    async def update(self, incident: Incident) -> Incident: ...


class ActionRepository(Protocol):
    async def list(self) -> builtins_list[Action]: ...
    async def create(self, action: Action) -> Action: ...


class ApprovalRepository(Protocol):
    async def list(self) -> builtins_list[Approval]: ...
    async def create(self, approval: Approval) -> Approval: ...


class AuditLogRepository(Protocol):
    async def list(self) -> builtins_list[AuditLog]: ...
    async def create(self, log: AuditLog) -> AuditLog: ...
